FROM centos:7
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && rpm -ivh http://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm \ 
    && yum install --downloadonly --downloaddir=/data/mysql mysql-community-server \
    && createrepo /data/mysql \
    && tar zcvf /data/repo.tar.gz /data/mysql \
    && rm -rf /data/mysql \
    && rm -rf /var/cache/yum
