FROM centos:7
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum install --downloadonly --downloaddir=/data/haproxy haproxy \
    && createrepo /data/haproxy \
    && tar zcvf /data/haproxy.tar.gz /data/haproxy \
    && rm -rf /data/haproxy \
    && rm -rf /var/cache/yum
