FROM centos:7
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \ 
    && yum install --downloadonly --downloaddir=/data/docker-ce docker-ce \
    && createrepo /data/docker-ce \
    && tar zcvf /data/repo.tar.gz /data/docker-ce \
    && rm -rf /data/docker-ce \
    && rm -rf /var/cache/yum
