FROM centos:7
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo \ 
    && yum install --downloadonly --downloaddir=/docker-ce docker-ce \
    && createrepo /docker-ce \
    && tar zcvf /repo.tar.gz /docker-ce
