FROM centos:7
RUN yum install yum-plugin-downloadonly yum-utils device-mapper-persistent-data lvm2 createrepo -y \
    && yum install --downloadonly --downloaddir=/data/keepalived keepalived \
    && createrepo /data/keepalived \
    && tar zcvf /data/keepalived.tar.gz /data/keepalived \
    && rm -rf /data/keepalived \
    && rm -rf /var/cache/yum
